/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package olinimageprocessor;

import olinimageprocessor.common.Const;
import olinimageprocessor.common.Const.ImageTypes;
import olinimageprocessor.common.Const.TypeNames;
import olinimageprocessor.common.ImageProperties;

/**
 *
 * @author Jeniffer
 */
public class TargetImage extends javax.swing.JInternalFrame {

    /**
     * Creates new form TargetImage
     */
    public static Main main;

    public TargetImage(Main main) {
        initComponents();
        this.main = main;
    }

    public void setSelectedType(ImageProperties prop) {
        this.main.setmImageProperties(prop);
        NewEditImage ned = new NewEditImage(main);
        this.main.getMainPane().add(ned);
        ned.show();
        ned.toFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btProduct = new javax.swing.JButton();
        btBanner = new javax.swing.JButton();
        btCategory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMinimumSize(new java.awt.Dimension(740, 520));
        setPreferredSize(new java.awt.Dimension(740, 520));

        btProduct.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btProduct.setText("Producto");
        btProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProductActionPerformed(evt);
            }
        });

        btBanner.setBackground(new java.awt.Color(255, 255, 255));
        btBanner.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btBanner.setText("Banner");
        btBanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBannerActionPerformed(evt);
            }
        });

        btCategory.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btCategory.setText("Categoria");
        btCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoryActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Destino de la imagen");

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("(logo)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(btProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCategoryActionPerformed
        // TODO add your handling code here:
         setSelectedType(new ImageProperties(
                ImageTypes.CATEGORIES.width, 
                ImageTypes.CATEGORIES.height, 
                TypeNames.TYPE__CATEGORIES));
        
    }//GEN-LAST:event_btCategoryActionPerformed

    private void btBannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBannerActionPerformed
        // TODO add your handling code here:

        setSelectedType(new ImageProperties(
                ImageTypes.BANNER.width, 
                ImageTypes.BANNER.height, 
                TypeNames.TYPE_BANNER));

    }//GEN-LAST:event_btBannerActionPerformed

    private void btProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProductActionPerformed
        // TODO add your handling code here:
         setSelectedType(new ImageProperties(
                ImageTypes.PRODUCT.width, 
                ImageTypes.PRODUCT.height, 
                TypeNames.TYPE_PRODUCT));
    }//GEN-LAST:event_btProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBanner;
    private javax.swing.JButton btCategory;
    private javax.swing.JButton btProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
